[View in Colaboratory](https://colab.research.google.com/github/dD2405/ML_ON1-Acadview/blob/master/Assignment_13.ipynb)

In [0]:
## 1) import the dataset from sklearn 

from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

In [0]:
var = load_digits()

In [16]:
# 2) Save X(features) and y(target) as dataframes. X is np.array(mnist.data) and y is mnist.target.

x = var.data
x.shape
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [17]:

y = var.target
y

array([0, 1, 2, ..., 8, 9, 8])

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn import model_selection
reg = LogisticRegression()

In [0]:
# 3) Split the dataset into training and testing sets

x_train , x_test , y_train , y_test = train_test_split(x, y , test_size = 0.30,random_state =2)

In [0]:
# 4) Use KNN

from sklearn.neighbors import KNeighborsClassifier 


In [25]:
classifier = KNeighborsClassifier(n_neighbors=5)  
classifier.fit(x_train, y_train)  

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [0]:
y_pred = classifier.predict(x_test)  

In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [31]:
confusion_matrix(y_test, y_pred)

array([[54,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 56,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 54,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 58,  0,  1,  0,  1,  1,  1],
       [ 0,  0,  0,  0, 51,  0,  0,  1,  1,  0],
       [ 0,  0,  0,  0,  0, 58,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 55,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 55,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0, 44,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  1,  1, 41]])

In [33]:
classification_report(y_test, y_pred)

'             precision    recall  f1-score   support\n\n          0       1.00      1.00      1.00        54\n          1       0.95      1.00      0.97        56\n          2       1.00      1.00      1.00        54\n          3       1.00      0.94      0.97        62\n          4       1.00      0.96      0.98        53\n          5       0.97      0.98      0.97        59\n          6       1.00      0.98      0.99        56\n          7       0.95      1.00      0.97        55\n          8       0.92      0.94      0.93        47\n          9       0.95      0.93      0.94        44\n\navg / total       0.97      0.97      0.97       540\n'